// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lume_sga.Data;

#nullable disable

namespace lume_sga.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("lume_sga.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrioridadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolucaoAplicada")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrioridadeId");

                    b.HasIndex("SetorId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("lume_sga.Models.Prioridade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoEstimadoHoras")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prioridades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Baixa",
                            TempoEstimadoHoras = 48
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Média",
                            TempoEstimadoHoras = 24
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Alta",
                            TempoEstimadoHoras = 4
                        });
                });

            modelBuilder.Entity("lume_sga.Models.Setor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("lume_sga.Models.Chamado", b =>
                {
                    b.HasOne("lume_sga.Models.Prioridade", "Prioridade")
                        .WithMany()
                        .HasForeignKey("PrioridadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lume_sga.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prioridade");

                    b.Navigation("Setor");
                });
#pragma warning restore 612, 618
        }
    }
}
